version: '3.5'
services:
  website:
    build: .
#    image: caixie-website:latest
    restart: 'unless-stopped'
    networks:
      - traefik
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.website0.middlewares=https-redirect@file"
      - "traefik.http.routers.website0.entrypoints=http"
      - "traefik.http.routers.website0.rule=Host(`caixie.top`, `www.caixie.top`, `caixie.ltd`)"
      - "traefik.http.routers.website1.middlewares=https-redirect@file"
      - "traefik.http.routers.website1.entrypoints=https"
      - "traefik.http.routers.website1.tls=true"
      - "traefik.http.routers.website1.rule=Host(`caixie.top`, `www.caixie.top`, `caixie.ltd`)"
      - "traefik.http.services.websitebackend.loadbalancer.server.scheme=http"
      - "traefik.http.services.websitebackend.loadbalancer.server.port=80"
        #- "traefik.http.routers.app_https.service=website"
#      - "traefik.http.services.website.loadbalancer.server.port=3000"
#      - "traefik.tcp.services.website.loadbalancer.server.port=3000"
      #volumes:
      #- ./:/app
networks:
  traefik:
    external: true
